### ISSUE TITLE
install_pkgs() prompts for every package install

### ISSUE THREAD

**Issue by toumban1** [ddsjoberg/updater#9]
When re-installing packages after updating to R 4.3.1, install_pkgs() provides prompts (Y/N) for each package that is installed. This stems from the update to renv::install() where interactive confirmation is now default in renv version 1.0.0. 

(https://rstudio.github.io/renv/reference/install.html)

**Comment by ddsjoberg** [comment]
oh boy, this is new in renv v1.0. 

to be frank, this is a tool i no longer use in my current role. Do you know if there is a way turn this off in renv?

**Comment by ddsjoberg** [comment]
I see there is now a `renv::install(prompt=FALSE)` argument.

**Comment by ddsjoberg** [comment]
@toumban1 can you please test the update here on your local machine?
https://github.com/ddsjoberg/updater/pull/10

**Comment by toumban1** [comment]
It looks good on my end. Thank you!
